/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux lappy-chisui 4.11.3-1-ARCH x86_64"
#define LGL_COMPILED "Fri Aug  4 14:06:45 CEST 2017"
#define LGL_RELEASED "Tue Apr 29 19:18:48 CEST 2014"
#define LGL_VERSION "ayv"
#define LGL_ID "86bf266b9332599f1b876e28a02fe8427aeaa2db"
